// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt5tocsV69rsTHyED6lH_gh1riS4WFppI',
    appId: '1:541806337014:web:582d77f6fd1d75267d45d7',
    messagingSenderId: '541806337014',
    projectId: 'expensetracker-48512',
    authDomain: 'expensetracker-48512.firebaseapp.com',
    storageBucket: 'expensetracker-48512.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuM9X9xGVCMxVXwX_gH1qZW6cqcfGcSK0',
    appId: '1:541806337014:android:583cbfd0fc025bed7d45d7',
    messagingSenderId: '541806337014',
    projectId: 'expensetracker-48512',
    storageBucket: 'expensetracker-48512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSW5eIfG4bCtiWdaHin6_TWJP3C9YFMQ',
    appId: '1:541806337014:ios:54eac14b52eddca47d45d7',
    messagingSenderId: '541806337014',
    projectId: 'expensetracker-48512',
    storageBucket: 'expensetracker-48512.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSW5eIfG4bCtiWdaHin6_TWJP3C9YFMQ',
    appId: '1:541806337014:ios:54eac14b52eddca47d45d7',
    messagingSenderId: '541806337014',
    projectId: 'expensetracker-48512',
    storageBucket: 'expensetracker-48512.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt5tocsV69rsTHyED6lH_gh1riS4WFppI',
    appId: '1:541806337014:web:5372b47d2ca458b67d45d7',
    messagingSenderId: '541806337014',
    projectId: 'expensetracker-48512',
    authDomain: 'expensetracker-48512.firebaseapp.com',
    storageBucket: 'expensetracker-48512.firebasestorage.app',
  );
}
